module.exports = [
  require('./americanexpress'),
  require('./bankofamerica'),
  require('./barclays'),
  require('./capitalonebank'),
  require('./chase'),
  require('./citibank'),
  require('./fifththird'),
  require('./googlewallet'),
  require('./hsbc'),
  require('./jpmorganchase'),
  require('./metabank'),
  require('./navyfederal'),
  require('./payoneer'),
  require('./suntrust'),
  require('./tdbank'),
  require('./usbank'),
  require('./wellsfargo')
];
